language: node_js
node_js:
  - stable
  - '6'
  - '4'
#  - '0.12'
matrix:
  include:
  - os: osx
    osx_image: xcode8.2
    env: CC="clang" CXX="clang++"
  - os: linux
    dist: trusty
    env:
    - CC="gcc-5" CXX="g++-5"
    - CC="clang-3.8" CXX="clang++-3.8"
cache:
  directories:
  - node_modules
  - $HOME/.yarn-cache
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - g++-5
install:
  - npm install -g node-gyp
after_success:
  - node-gyp configure build
